#!/bin/bash

#=================================================
# GENERIC START
#=================================================

# IMPORT GENERIC HELPERS
source /usr/share/yunohost/helpers

# Load common variables and helpers
source ./_common.sh

#=================================================
# STANDARD REMOVE
#=================================================

# Stop & remove Drone
systemctl stop "$app".service || docker stop $app
docker rm "$app"
docker rmi "$DRONE_IMAGE"

# Drop MySQL database and user
ynh_mysql_drop_db "$dbname" 2>/dev/null
ynh_mysql_drop_user "$dbuser" 2>/dev/null

# Retrieve domain from app settings
domain=$(ynh_app_setting_get "$app" domain)

# Delete app directory and configurations
ynh_secure_remove "$final_path"

# Remove init script
ynh_remove_systemd_config

 # Remove nginx config
ynh_remove_nginx_config

# Remove monitor
yunohost service remove "$app"

true # Do not fail if remove after install error
