#!/bin/bash

#=================================================
# GENERIC START
#=================================================

# IMPORT GENERIC HELPERS
source /usr/share/yunohost/helpers

# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

# Load common variables and helpers
source ../settings/scripts/_common.sh

domain=$(ynh_app_setting_get "$app" domain)
admin=$(ynh_app_setting_get "$app" adminusername)
dbpass=$(ynh_app_setting_get "$app" mysqlpwd)
port=$(ynh_app_setting_get "$app" web_port)
is_public=$(ynh_app_setting_get "$app" is_public)

# Check domain/path availability with app helper
ynh_webpath_available $domain $path_url || ynh_die "$domain is not available as domain, please use an other domain."

# Check user parameter
ynh_user_exists "$admin" \
  || ynh_die "The chosen admin user does not exist."

# Check Final Path availability
[ ! -e "$final_path" ] || ynh_die "This path already contains a folder"

# Check configuration files
nginx_conf="/etc/nginx/conf.d/${domain}.d/${app}.conf"
[[ -f $nginx_conf ]] && ynh_die \
"The NGINX configuration already exists at '${nginx_conf}'.
You should safely delete it before restoring this app."

#=================================================
# STANDARD RESTORATION STEPS
#=================================================

# Restore all files
ynh_restore

# Create and restore the database
ynh_mysql_create_db "$dbname" "$dbuser" "$dbpass"
ynh_mysql_connect_as "$dbuser" "$dbpass" "$dbname" < ./db.sql

# Restore systemd files
systemctl daemon-reload
systemctl enable "$app".service

#=================================================
# GENERIC FINALIZATION
#=================================================

# Unprotect root from SSO if public
set_access_settings

sudo yunohost service add "$app"

# Reload services
sudo systemctl reload nginx.service || true
sudo systemctl restart "$app".service || true
